### ISSUE TITLE
 Maximum call stack size exceeded duto preact-render-to-string

### ISSUE THREAD

**Issue by lazidoca** [aomkirby123/nextjs-preactX#10]
I got the error when trying to run the project. Here is the call stack:

RangeError: Maximum call stack size exceeded
    at f (js\nextjs-preactX\node_modules\preact-render-to-string\dist\index.js:1:859)
    at Array.reduce (<anonymous>)
    at f (js\nextjs-preactX\node_modules\preact-render-to-string\dist\index.js:1:891)
    at Array.reduce (<anonymous>)
    at f (js\nextjs-preactX\node_modules\preact-render-to-string\dist\index.js:1:891)
    at Array.reduce (<anonymous>)
    at f (js\nextjs-preactX\node_modules\preact-render-to-string\dist\index.js:1:891)
    at Array.reduce (<anonymous>)
    at f (js\nextjs-preactX\node_modules\preact-render-to-string\dist\index.js:1:891)
    at Array.reduce (<anonymous>)
    at f (js\nextjs-preactX\node_modules\preact-render-to-string\dist\index.js:1:891)
    at Array.reduce (<anonymous>)
    at f (js\nextjs-preactX\node_modules\preact-render-to-string\dist\index.js:1:891)
    at Array.reduce (<anonymous>)
    at f (js\nextjs-preactX\node_modules\preact-render-to-string\dist\index.js:1:891)
    at Array.reduce (<anonymous>)

Do you have any idea please?

**Comment by aomkirby123** [comment]
Hello @lazidoca and thanks for interested in PreactX with Next.js! 
I sometimes have a weird issue like this one too! And I'm here to help as much as I can~
  
There's a lot of way of getting an error from `preact-render-to-string` but   I often get an error from `preact-render-to-string` too, so I gathered some common approach for resolving this error. Your error might be solved by some of these fixes:
  
1) Check the installed version of preact-render-to-string. preact-render-to-string only worked on Preact X on version 5.x.x and beyond but the `latest` tag on npm is set as 4.1.0 and if this is the case, you should try installing `next` tag of preact-render-to-string by:
```
npm install preact-render-to-string@next
// using yarn
yarn add preact-render-to-string@next
```
Run the dev server again to see if this solve your problem.
  
2) Check the installed version of Preact X. Lastest version of Preact X is rc.2, consider upgrading it to see if it work.
```
npm install preact-render-to-string@next
// using yarn
yarn add preact-render-to-string@next
```
  
3) If you don't use a custom server, try to remove preact/hooks usage from your file and see if you still get the error. If it works, skip to the last step. If not follow the next step.
  
4) If you use a custom server, check if you add `require("module-alias/register") on the top of the server file. Also, check if you added this in your package.json:
```javascript
"_moduleAliases": {
    "react": "node_modules/preact/compat",
    "react-dom": "node_modules/preact/compat",
    "react-ssr-prepass": "node_modules/preact-ssr-prepass"
  }
```
And check if you add this in your server file:
```javascript
require("module-alias/register")
```
This will alias react-ssr-prepass to preact-ssr-prepass for using with server-side-rendering.
  
5) Open `next.config.js`, replace with this:
```javascript
// next.config.js
module.exports = {
    target: 'serverless',
    webpack (config, options) {
        config.resolve.alias['react'] = 'preact/compat'
        config.resolve.alias['react-dom'] = 'preact/compat'

        return config
    }
}
```
  
6) Use preact/compat instead. I suggest that you should try import from 'react' instead of 'preact' and see if it work since we already aliased React and React DOM to preact/compat. By doing this, Preact is still being used by imported not React but with the help of Preact compat for compatibility. Preact Compat is a compatibility layer when using Preact with a library which created to be used with React. Building this to production is still Preact instead of React. This should resolve most error occurs with Preact. This method is suggested by Preact's core team as well:
![Twitter](https://user-images.githubusercontent.com/35027979/64614213-2a86a100-d402-11e9-9656-518be8981631.png)
  
If none of above method solved the issue, providing `package.json` would be great for figuring out what is happening and we might help you resolve the problem faster.
Also, could you describe if you use some library then the error occurs or trying to set up Preact with Next yourself then this occurs and if you use a custom server or not, would be a great help for other people who might find the weird error like this~
Feels free to question anything here, I'm glad I could help you, cheers!

**Comment by lazidoca** [comment]
Hi, thanks for your reply. Actually I cloned this repository and got the error when I try to start it.

**Comment by aomkirby123** [comment]
Hello again! And thanks for the information~
This case is pretty weird. I had just re-cloned and try available dev option: `dev` and `next` and turn out no error.
But don't worry, I need a little of your help that might solve the problem.
  
1) Consider updating your node.js might help to solve the problem since next.js perform best at node 8 or above. Some options can't be used when node.js is lower than 8. This might be the case but I'm just guessing.
You can check your node.js version by:
```
node -v
```
I consider updating to Node 10 though.
  
2) Have you try cloning this repository and start without editing anything? If not so, did you add react hook? If you did, you need a custom server to alias the hook.
  
3) Delete node_modules folder, yarn.lock and re-install all dependencies might help to solve your problem.
  
If everything is not working, I'd considering trying installing from something like docker might be a good idea too. Cheers!

**Comment by lazidoca** [comment]
My node version is v10.16.0

I cloned this repo and just run `npm install` and then `npm run dev`
